[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Form handling
[forms]
  contact = "/contact"

# Form notifications - Everguard will get email notifications
[[forms.contact.notifications]]
  type = "email"
  to = "info@everguardgroup.com.au"
  subject = "🚨 New Contact Form Submission - Everguard Intelligence"
  template = """
New contact form submission received:

Name: {{ name }}
Email: {{ email }}
Phone: {{ phone }}
Company: {{ company }}
Service: {{ service }}
Urgency: {{ urgency }}
Budget: {{ budget }}

Message:
{{ message }}

Submitted: {{ dateTime }}
  """

# Handle client-side routing for static export
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"